name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Generate Snake
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Sivaraj16
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=0x39D353&color_dots=#39D353,#26A641,#006D32,#0E4429&background=#0D1117
            dist/github-contribution-grid-snake.gif?color_snake=0x39D353&color_dots=#39D353,#26A641,#006D32,#0E4429&background=#0D1117
          
      # Deploy to GitHub Pages
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "Sivaraj16"
          git config --global user.email "sivaraj16012005@gmail.com"
          git add .
          git commit -m "Generate Snake Animation"
          git push origin output
